nodeLinker: pnp
pnpMode: loose

packageExtensions:
  "@storybook/nextjs@*":
    dependencies:
      "webpack": "*"
  "@chromatic-com/storybook@*":
    dependencies:
      "@storybook/client-logger": "*"
      "@storybook/core-events": "*"
  "@npmcli/config@*":
    dependencies:
      "yargs": "*"
