name: Auto approve Hotfix PRs
on: 
  pull_request:
    branches:
      - main
    types: [opened, reopened]

permissions:
      pull-requests: write
      contents: read

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from hotfix/*
        id: check-branch
        run: echo "hotfix_branch=$(echo ${{ github.head_ref }} | grep -E '^hotfix/')" >> $GITHUB_ENV

      - name : Auto Approve PR
        if: env.hotfix_branch
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.PAT_AUTO_APPROVE }}
          review-message: "Auto approved automated PR"
        
