name: Auto Approve Hotfix PRs

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened]

jobs:
  auto-approve:
    if: startsWith(github.head_ref, 'hotfix/')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Auto Approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
